### ISSUE TITLE
ValueError:  All the 1215 fits failed for xgboost classifier.

### ISSUE THREAD

**Issue by anesheim-uni** [SW8-Mobility/speed_limit_floating_car_data#59]
We get the following error message when calling .fit() on the xgboost classifier:
```
ValueError: 
All the 1215 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1215 fits failed with the following error:
Traceback (most recent call last):
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\xgboost\core.py", line 620, in inner_f
    return func(**kwargs)
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\xgboost\sklearn.py", line 1440, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0], got [50]
```

**Comment by anesheim-uni** [comment]
Trying to fit on bad data is the reason for the issue.
