### ISSUE TITLE
ValueError: All the fits failed for logistic regression classifier.

### ISSUE THREAD

**Issue by anesheim-uni** [SW8-Mobility/speed_limit_floating_car_data#60]
We get the following error message when calling .fit() on the logistic regression classifier.
```
ValueError: 
All the 90 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
75 fits failed with the following error:
TypeError: float() argument must be a string or a real number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1196, in fit
    X, y = self._validate_data(
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\sklearn\base.py", line 584, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\sklearn\utils\validation.py", line 1106, in check_X_y
    X = check_array(
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\sklearn\utils\validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\sklearn\utils\_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\pandas\core\generic.py", line 1998, in __array__
    arr = np.asarray(values, dtype=dtype)
ValueError: setting an array element with a sequence.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "..\speed_limit_floating_car_data\venv\lib\site-packages\sklearn\linear_model\_logistic.py", line 64, in _check_solver
    raise ValueError(
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.
```

**Comment by anesheim-uni** [comment]
Trying to fit on bad data is the reason for the issue.
